export const companies = [
  {
    id: 1,
    name: 'Lavadoras del Norte',
    description: 'Empresa especializada en alquiler de lavadoras de alta eficiencia.',
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=500&q=80',
    rating: 4.5,
    location: 'Centro Comercial Santafé - Bogotá',
    phone: '3001234567',
    email: 'contacto@lavadorasnorte.com',
    services: ['Lavado general', 'Lavado en seco', 'Planchado'],
    tags: ['Verificada', 'Abierta'],
    distance: 1.2,
    avgTime: 45,
    minPrice: 2500,
    isOpen: true,
    verified: true,
    reviewCount: 128,
    coordinates: { lat: 4.6543, lng: -74.0592 },
  },
  {
    id: 2,
    name: 'EcoLavandería SAS',
    description: 'Servicio ecológico con máquinas de bajo consumo de agua y energía.',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=500&q=80',
    rating: 4.8,
    location: 'Centro Comercial Unicentro - Bogotá',
    phone: '3007654321',
    email: 'info@ecolavanderia.com',
    services: ['Lavado ecológico', 'Lavado express', 'Desinfección'],
    tags: ['Verificada', 'Express', 'A domicilio', 'Abierta'],
    distance: 2.5,
    avgTime: 30,
    minPrice: 3000,
    isOpen: true,
    verified: true,
    reviewCount: 245,
    coordinates: { lat: 4.6689, lng: -74.0584 },
  },
  {
    id: 3,
    name: 'LavaRápido 24/7',
    description: 'Servicio de lavandería automática disponible las 24 horas.',
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=500&q=80',
    rating: 4.2,
    location: 'Chapinero Alto - Bogotá',
    phone: '3109876543',
    email: 'contacto@lavarapido.com',
    services: ['Autoservicio', 'Lavado premium', 'Secado'],
    tags: ['Económico', 'Abierta'],
    distance: 0.8,
    avgTime: 60,
    minPrice: 2000,
    isOpen: true,
    verified: false,
    reviewCount: 89,
    coordinates: { lat: 4.6456, lng: -74.0645 },
  },
  {
    id: 4,
    name: 'Clean & Go Express',
    description: 'Lavandería exprés con servicio de recogida y entrega el mismo día.',
    image: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=500&q=80',
    rating: 4.6,
    location: 'Usaquén - Bogotá',
    phone: '3201112233',
    email: 'hola@cleanandgo.com',
    services: ['Lavado exprés', 'Planchado', 'Doblez'],
    tags: ['Verificada', 'Express', 'Premium', 'Abierta'],
    distance: 3.1,
    avgTime: 25,
    minPrice: 3500,
    isOpen: true,
    verified: true,
    reviewCount: 312,
    coordinates: { lat: 4.6956, lng: -74.0334 },
  },
  {
    id: 5,
    name: 'Lavandería EcoSmart',
    description: 'Lavandería sostenible con productos biodegradables y máquinas eficientes.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=500&q=80',
    rating: 4.4,
    location: 'Suba - Bogotá',
    phone: '3104455667',
    email: 'info@ecosmart.com',
    services: ['Lavado ecológico', 'Desinfección', 'Planchado'],
    tags: ['Verificada', 'A domicilio', 'Recogida incluida'],
    distance: 4.2,
    avgTime: 50,
    minPrice: 2800,
    isOpen: false,
    verified: true,
    reviewCount: 76,
    coordinates: { lat: 4.7356, lng: -74.0892 },
  },
  {
    id: 6,
    name: 'SuperLavado Premium',
    description: 'Servicio premium de lavandería con máquinas de última generación.',
    image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=500&q=80',
    rating: 4.9,
    location: 'Chapinero - Bogotá',
    phone: '3157788990',
    email: 'contacto@superlavado.com',
    services: ['Lavado premium', 'Lavado en seco', 'Planchado', 'Perfumado'],
    tags: ['Verificada', 'Premium', 'Express', 'Abierta'],
    distance: 1.8,
    avgTime: 40,
    minPrice: 4000,
    isOpen: true,
    verified: true,
    reviewCount: 456,
    coordinates: { lat: 4.6345, lng: -74.0723 },
  },
  {
    id: 7,
    name: 'Wash & Fold Express',
    description: 'Lavandería rápida con servicio de lavado y doblez en menos de 2 horas.',
    image: 'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=500&q=80',
    rating: 4.7,
    location: 'Teusaquillo - Bogotá',
    phone: '3172233445',
    email: 'express@washandfold.com',
    services: ['Lavado exprés', 'Doblez', 'A domicilio'],
    tags: ['Verificada', 'Express', 'A domicilio', 'Recogida incluida', 'Abierta'],
    distance: 2.0,
    avgTime: 20,
    minPrice: 3200,
    isOpen: true,
    verified: true,
    reviewCount: 198,
    coordinates: { lat: 4.6156, lng: -74.0689 },
  },
  {
    id: 8,
    name: 'Lavandería Rápida y Fácil',
    description: 'Lavandería económica con servicio autoservicio y asistido.',
    image: 'https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?auto=format&fit=crop&w=500&q=80',
    rating: 4.1,
    location: 'Kennedy - Bogotá',
    phone: '3198877665',
    email: 'info@rapidayfacil.com',
    services: ['Autoservicio', 'Lavado general', 'Secado'],
    tags: ['Económico', 'Abierta'],
    distance: 5.0,
    avgTime: 35,
    minPrice: 2200,
    isOpen: true,
    verified: false,
    reviewCount: 54,
    coordinates: { lat: 4.6245, lng: -74.1523 },
  },
];

export const services = [
  {
    id: 1,
    name: 'LG WashTower Premium',
    status: 'Disponible',
    description: 'Lavadora de carga frontal con tecnología AI DD y control inteligente.',
    location: 'Centro Comercial Santafé - Bogotá',
    capacity: '12 kg',
    price: 3000,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=500&q=80',
    companyId: 1,
    tags: ['Premium', 'A domicilio'],
    timeEstimate: 120,
  },
  {
    id: 2,
    name: 'Samsung EcoBubble',
    status: 'Disponible',
    description: 'Lavadora con tecnología EcoBubble que lava eficazmente con burbujas.',
    location: 'Centro Comercial Unicentro - Bogotá',
    capacity: '10 kg',
    price: 3000,
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=500&q=80',
    companyId: 2,
    tags: ['Express', 'Recogida incluida'],
    timeEstimate: 60,
  },
  {
    id: 3,
    name: 'Mabe Carga Superior 17kg',
    status: 'En mantenimiento',
    description: 'Lavadora automática con sistema de lavado por agitador y gran capacidad.',
    location: 'Chapinero Alto - Bogotá',
    capacity: '17 kg',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=500&q=80',
    companyId: 3,
    tags: ['Económico', 'Gran capacidad'],
    timeEstimate: 180,
  },
  {
    id: 4,
    name: 'Whirlpool Supreme Care',
    status: 'Disponible',
    description: 'Lavadora de carga superior con sistema de limpieza profunda y ciclo rápido.',
    location: 'Centro Comercial Santafé - Bogotá',
    capacity: '15 kg',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=500&q=80',
    companyId: 1,
    tags: ['Premium', 'Disponible hoy'],
    timeEstimate: 90,
  },
  {
    id: 5,
    name: 'Lavado Express 30min',
    status: 'Disponible',
    description: 'Servicio exprés de lavado en solo 30 minutos. Ideal para prendas urgentes.',
    location: 'Centro Comercial Unicentro - Bogotá',
    capacity: '6 kg',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=500&q=80',
    companyId: 2,
    tags: ['Express', 'Más solicitado'],
    timeEstimate: 30,
  },
  {
    id: 6,
    name: 'Recogida y Entrega Full',
    status: 'Disponible',
    description: 'Programa la recogida de tu ropa y recíbela limpia y planchada en la puerta de tu casa.',
    location: 'Chapinero Alto - Bogotá',
    capacity: '20 kg',
    price: 8000,
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=500&q=80',
    companyId: 3,
    tags: ['A domicilio', 'Recogida incluida', 'Más solicitado'],
    timeEstimate: 240,
  },
];

export const appointments = [
  {
    id: 1,
    serviceId: 1,
    serviceName: 'LG WashTower Premium',
    date: '2026-07-10',
    time: '14:00',
    status: 'pendiente',
    address: 'Calle 123 #45-67',
    notes: 'Llegar antes de las 2pm',
    price: 3000,
  },
  {
    id: 2,
    serviceId: 2,
    serviceName: 'Samsung EcoBubble',
    date: '2026-07-08',
    time: '10:00',
    status: 'en_proceso',
    address: 'Carrera 5 #20-30',
    notes: '',
    price: 3000,
  },
  {
    id: 3,
    serviceId: 4,
    serviceName: 'Whirlpool Supreme',
    date: '2026-07-05',
    time: '09:00',
    status: 'finalizado',
    address: 'Avenida 10 #50-60',
    notes: 'Servicio completado',
    price: 3500,
  },
];

export const users = [
  {
    id: 1,
    name: 'Juan Pérez',
    email: 'juan@email.com',
    phone: '3001112233',
    role: 'cliente',
  },
  {
    id: 2,
    name: 'Admin Servilavadora',
    email: 'admin@servilavadora.com',
    phone: '3009998877',
    role: 'administrador',
  },
];

export const onboardingSlides = [
  {
    id: 1,
    title: 'Bienvenido a Servilavadora',
    description: 'La forma más fácil de alquilar lavadoras de alta calidad por horas.',
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 2,
    title: 'Encuentra lavadoras cerca',
    description: 'Busca y encuentra lavadoras disponibles cerca de tu ubicación.',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 3,
    title: 'Reserva y lava',
    description: 'Selecciona la lavadora, el horario y disfruta de ropa limpia y fresca.',
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=500&q=80',
  },
];

export const benefits = [
  { icon: 'clock-outline', title: 'Ahorra Tiempo', description: 'Evita largos viajes a lavanderías tradicionales' },
  { icon: 'cash', title: 'Precios Justos', description: 'Solo $3.000 por hora, máximo 4 horas de uso' },
  { icon: 'map-marker', title: 'Ubicaciones Cercanas', description: 'Encuentra lavadoras cerca de tu ubicación' },
  { icon: 'shield-check', title: 'Garantía de Calidad', description: 'Lavadoras modernas y en perfecto estado' },
];
